name: flutter_weather
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/clear.png
    - assets/images/cloudy.png
    - assets/images/rainy.png
    - assets/images/snow.png
    - assets/images/thunderstorm.png
